/** @vitest-environment jsdom */
import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { AuthUser, QualityExecutionView, Role } from '@erve/types';
import { apiClient } from '../../lib/api-client.js';
import * as AuthContext from '../../auth/AuthContext.js';
import { QualityExecutionPage } from './QualityExecutionPage.js';

let container: HTMLDivElement;
let root: Root;
beforeEach(() => {
  container = document.createElement('div');
  document.body.appendChild(container);
  root = createRoot(container);
});
afterEach(() => {
  act(() => root.unmount());
  container.remove();
  vi.restoreAllMocks();
});
const view: QualityExecutionView = {
  id: 'e1',
  jobOrderId: 'j1',
  jobOrderNumber: 'JO-2026-000001',
  processFlowActivityId: 'a1',
  activityName: 'Inline Inspection',
  qualityForm: {
    id: 'f1',
    code: 'INLINE',
    name: 'Inline Inspection Report',
    versionId: 'v1',
    versionNumber: 1,
  },
  attemptNumber: 1,
  batchNumber: 1,
  inspectedQuantity: null,
  ppSample: null,
  productionContext: null,
  coverage: null,
  status: 'DRAFT',
  version: 1,
  startedAt: '',
  finalizedAt: null,
  sections: [
    {
      id: 's1',
      sequence: 1,
      title: 'Conclusion',
      components: [{ id: 'c1', sequence: 1, type: 'COMMENTS', title: 'Comments', config: {} }],
    },
  ],
  responses: {
    expectedVersion: 1,
    checklistResponses: [],
    aqlResults: [],
    defects: [],
    correctiveActions: [],
    testResults: [],
    quantities: [],
    comments: [],
    fieldResponses: [],
    attendees: [],
    actions: [],
    signoffs: [],
    outcome: null,
  },
  attachments: [],
};

describe('web Quality execution workflow', () => {
  it('renders with no AuthProvider present (useOptionalAuth), without throwing and without a PDF generatedBy button', async () => {
    // This page reads `useOptionalAuth()?.user?.name` only to label the PDF export's
    // "generated by" field — it must never require an AuthProvider to render, unlike the
    // hard-throwing useAuth(). No test in this file wraps <QualityExecutionPage> in an
    // AuthProvider, so this also implicitly covers every other test below.
    vi.spyOn(apiClient, 'get').mockResolvedValue({ data: { data: view } });
    await act(async () => {
      root.render(
        <QueryClientProvider
          client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
        >
          <MemoryRouter initialEntries={['/quality-executions/e1']}>
            <Routes>
              <Route path="/quality-executions/:executionId" element={<QualityExecutionPage />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      );
    });
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    expect(container.querySelector('[data-quality-execution-shell="true"]')).not.toBeNull();
    const downloadButton = [...container.querySelectorAll('button')].find((button) =>
      button.textContent?.includes('Download PDF'),
    );
    expect(downloadButton).toBeDefined();
  });

  it.each([
    ['Inline Inspection', 'Inline Inspection Report', 'Inline Inspection'],
    ['Final Inspection', 'Final Inspection Report', 'Final Inspection'],
    [
      'SIZE SET / PRE-PRODUCTION REPORT',
      'Pre-Production Meeting Report',
      'Size Set / Pre-Production Report',
    ],
  ])('renders %s in the shared execution shell', async (activityName, formName, title) => {
    vi.spyOn(apiClient, 'get').mockResolvedValue({
      data: {
        data: {
          ...view,
          activityName,
          qualityForm: { ...view.qualityForm, name: formName },
        },
      },
    });
    await act(async () => {
      root.render(
        <QueryClientProvider
          client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
        >
          <MemoryRouter initialEntries={['/quality-executions/e1']}>
            <Routes>
              <Route path="/quality-executions/:executionId" element={<QualityExecutionPage />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      );
    });
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0));
    });

    expect(container.querySelector('[data-quality-execution-shell="true"]')).not.toBeNull();
    expect(container.querySelector('h1')?.textContent).toBe(title);
    expect(container.textContent).toContain(`${formName} v1 · Attempt 1 · DRAFT`);
    const back = container.querySelector('a[aria-label="Back to Job Order JO-2026-000001"]');
    expect(back?.textContent).toContain('←');
    expect(back?.textContent).toContain('Job Order JO-2026-000001');
    expect(back?.getAttribute('href')).toBe('/job-orders/j1');
  });

  it('renders the draft and saves through the optimistic-version endpoint', async () => {
    // UXAUTH-006: mutating now requires an actual mutation-capable caller
    // (canMutateQualityExecution) — the real route guard already ensures
    // only ADMIN/QA_USER/MERCHANDISER/SENIOR_MANAGEMENT ever reach this page,
    // and only ADMIN/QA_USER may mutate, so this Save-flow test mocks a
    // QA_USER the same way production always has one by the time this page
    // mounts.
    vi.spyOn(AuthContext, 'useOptionalAuth').mockReturnValue({
      user: { id: 'user-1', email: 'qa@test.local', mobile: null, name: 'QA User', roles: ['QA_USER'] },
      token: 'valid-token',
      login: vi.fn(),
      logout: vi.fn(),
      refreshUser: vi.fn(),
      isInitializing: false,
    } as unknown as ReturnType<typeof AuthContext.useOptionalAuth>);
    vi.spyOn(apiClient, 'get').mockResolvedValue({ data: { data: view } });
    const put = vi
      .spyOn(apiClient, 'request')
      .mockResolvedValue({ data: { data: { ...view, version: 2 } } });
    await act(async () => {
      root.render(
        <QueryClientProvider
          client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
        >
          <MemoryRouter initialEntries={['/quality-executions/e1']}>
            <Routes>
              <Route path="/quality-executions/:executionId" element={<QualityExecutionPage />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      );
    });
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    expect(container.textContent).toContain('Inline Inspection Report v1');
    await act(async () => {
      [...container.querySelectorAll('button')]
        .find((button) => button.textContent === 'Save draft')
        ?.click();
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    expect(put).toHaveBeenCalledWith(
      expect.objectContaining({
        method: 'put',
        url: '/quality-executions/e1',
        data: expect.objectContaining({ expectedVersion: 1 }),
      }),
    );
  });

  it('shows immutable physical-batch history and starts reinspection without new quantities', async () => {
    // UXAUTH-006: reinspection is a mutation action (QA_OPERATION_ROLES) —
    // mock a QA_USER the same way production always has one by the time this
    // page mounts (see the Save-flow test above).
    vi.spyOn(AuthContext, 'useOptionalAuth').mockReturnValue({
      user: { id: 'user-1', email: 'qa@test.local', mobile: null, name: 'QA User', roles: ['QA_USER'] },
      token: 'valid-token',
      login: vi.fn(),
      logout: vi.fn(),
      refreshUser: vi.fn(),
      isInitializing: false,
    } as unknown as ReturnType<typeof AuthContext.useOptionalAuth>);
    const failed: QualityExecutionView = {
      ...view,
      status: 'FINALIZED',
      inspectedQuantity: 15,
      responses: {
        ...view.responses,
        outcome: { componentId: 'outcome', value: 'FAIL' },
      },
      finalBatch: {
        id: 'batch-3',
        batchNumber: 3,
        physicalQuantity: 15,
        disposition: 'AWAITING_REINSPECTION',
        allocations: [
          {
            jobOrderLineSizeId: 'size-s',
            sizeCode: 'S',
            sizeLabel: 'Small',
            quantity: 5,
          },
          {
            jobOrderLineSizeId: 'size-m',
            sizeCode: 'M',
            sizeLabel: 'Medium',
            quantity: 10,
          },
        ],
        attempts: [
          {
            id: 'e1',
            attemptNumber: 1,
            status: 'FINALIZED',
            outcome: 'FAIL',
            rejectionReason: 'Broken zipper',
            startedAt: '2026-08-24T00:00:00.000Z',
            finalizedAt: '2026-08-24T01:00:00.000Z',
          },
        ],
        release: null,
      },
    };
    vi.spyOn(apiClient, 'get').mockResolvedValue({ data: { data: failed } });
    const post = vi.spyOn(apiClient, 'post').mockResolvedValue({
      data: { data: { ...failed, id: 'e2', attemptNumber: 2, status: 'DRAFT' } },
    });
    await act(async () => {
      root.render(
        <QueryClientProvider
          client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
        >
          <MemoryRouter initialEntries={['/quality-executions/e1']}>
            <Routes>
              <Route path="/quality-executions/:executionId" element={<QualityExecutionPage />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      );
    });
    await vi.waitFor(() => expect(container.textContent).toContain('Physical Final batch 3'));
    expect(container.textContent).toContain('S · Small5');
    expect(container.textContent).toContain('Attempt 1FAIL');
    expect(container.textContent).toContain('Rejection / Defect Reason: Broken zipper');
    expect(container.querySelector('input[aria-label^="Final batch quantity"]')).toBeNull();
    const reinspectButton = [...container.querySelectorAll('button')].find(
      (button) => button.textContent === 'Start reinspection',
    ) as HTMLButtonElement;
    expect(reinspectButton.disabled).toBe(false);
    await act(async () => {
      reinspectButton.click();
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    expect(post).toHaveBeenCalledWith(
      '/quality-executions/final-batches/batch-3/reinspect',
      undefined,
    );
  });
});

// UXAUTH-006: MERCHANDISER/SENIOR_MANAGEMENT can read a generic
// QualityExecution (GET is allowed for both — see
// apps/api/src/modules/quality-executions/quality-executions.routes.ts) but
// every mutation endpoint (PUT save, POST finalize/attachments,
// DELETE attachments, POST final-batches/.../reinspect|cancel|permanently-reject)
// is restricted to ADMIN/QA_USER only. This page must wire canMutate from the
// real caller's role so the read-only roles never see Save/Finalize.
describe('web Quality execution role-gated mutation controls (UXAUTH-006)', () => {
  function mockUser(role: Role) {
    const user: AuthUser = { id: 'user-1', email: 'user@test.local', mobile: null, name: 'Test User', roles: [role] };
    vi.spyOn(AuthContext, 'useOptionalAuth').mockReturnValue({
      user,
      token: 'valid-token',
      login: vi.fn(),
      logout: vi.fn(),
      refreshUser: vi.fn(),
      isInitializing: false,
    } as unknown as ReturnType<typeof AuthContext.useOptionalAuth>);
  }

  async function renderAs(role: Role) {
    mockUser(role);
    vi.spyOn(apiClient, 'get').mockResolvedValue({ data: { data: view } });
    await act(async () => {
      root.render(
        <QueryClientProvider
          client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}
        >
          <MemoryRouter initialEntries={['/quality-executions/e1']}>
            <Routes>
              <Route path="/quality-executions/:executionId" element={<QualityExecutionPage />} />
            </Routes>
          </MemoryRouter>
        </QueryClientProvider>,
      );
    });
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
  }

  it.each(['MERCHANDISER', 'SENIOR_MANAGEMENT'] as const)(
    '%s can read the execution but sees no mutation control',
    async (role) => {
      await renderAs(role);
      expect(container.textContent).toContain('Inline Inspection Report');
      const buttons = [...container.querySelectorAll('button')].map((b) => b.textContent);
      expect(buttons).not.toContain('Save draft');
      expect(buttons).not.toContain('Finalize');
    },
  );

  it.each(['ADMIN', 'QA_USER'] as const)(
    '%s (a generic execution mutation role) still sees Save/Finalize',
    async (role) => {
      await renderAs(role);
      const buttons = [...container.querySelectorAll('button')].map((b) => b.textContent);
      expect(buttons).toContain('Save draft');
      expect(buttons).toContain('Finalize');
    },
  );
});
