packages:
  - "apps/*"
  - "packages/*"
strictPeerDependencies: false
autoInstallPeers: true
shamefullyHoist: false
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
patchedDependencies:
  native-run@2.0.3: patches/native-run@2.0.3.patch
