ALTER TYPE "QaReworkStatus" RENAME VALUE 'PENDING_ACKNOWLEDGEMENT' TO 'REWORK_REQUIRED';
ALTER TYPE "QaReworkStatus" RENAME VALUE 'CLOSED' TO 'REINSPECTED';

ALTER TABLE "qa_rework_tasks"
  ALTER COLUMN "status" SET DEFAULT 'REWORK_REQUIRED';
